############
# Funnotate
############

# Table of gene families, from LIS data store
gene_families_data: /home/gene-families/21_hmmemit_consen.ahrd.tsv

# General settings
num_threads: 5
# error_log: [...]

# ESTScan
estscan:
  exe: /home/estscan/estscan
  matrix: /home/smat/medicago.smat

# BLAST: expects the databases in indexed format (.phr, .pin, .psq)
blast:
  exe: /home/blast/bin/blastall
  # To use blastp [...] instead of blastall -p blastp [...],
  # exe: /usr/bin/blastp
  dbs:
    - /home/blast-dbs/TAIR10_pep_20101209
    - /home/blast-dbs/Glyma.refseq_protein.fasta
    - /home/blast-dbs/Mt4.0v1_GenesProteinSeq_20130731_1800.fasta

# AHRD
ahrd:
  java: /usr/bin/java
  jar: /home/AHRD/ahrd.jar
  yml: /home/AHRD/ahrd_nosp_funnotate.yml

# InterPro
interpro:
  exe: /home/interproscan/interproscan.sh
  params: -appl TIGRFAM,SMART,SUPERFAMILY,Gene3D,PIRSF,Pfam,Coils

# HMMer
hmmer:
  exe: /home/hmmer/binaries/hmmscan
  db: /home/hmmdb/legume.fam3.VLMQ/legume.fam3.hmm
  # Unused:
  # params: [...]
  # target_families: [...]/07_family_fasta

# Lorax
lorax:
  url: lorax-flask-1:8000
  # args: [...]

############

