############
# Funnotate
############

# General settings

# override with environment variable FUNNOTATE_NUM_THREADS
num_threads: 5
# error_log: temp/funnotate.err

# ESTScan
estscan:
  exe: estscan
  matrix: /home/svengato/smat/medicago.smat

# BLAST: expects the databases in indexed format (.phr, .pin, .psq)
blast:
  # exe: /erdos/adf/e00/adf/blast-2.2.23/bin/blastall
  # To use blastp [...] instead of blastall -p blastp [...],
  exe: blastp
  dbs:
    - /srv/shiny-server/blastdb/TAIR10_pep_20101214
    - /srv/shiny-server/blastdb/GCF_000004515.5_Glycine_max_v2.1_protein.faa
    - /srv/shiny-server/blastdb/Mt4.0v2_GenesProteinSeq_20140818_1100.fasta

# AHRD
ahrd:
  java: java
  jar: /srv/shiny-server/ahrd.jar
  # Possible alternatives?
  # java: /erdos/adf/sw/jdk1.7.0/bin/java
  # jar: /erdos/adf/e01/lis/AHRD/2.0-stable/bin/ahrd.jar
  yml: /srv/shiny-server/ahrd/ahrd_nosp.yml

# InterPro
interpro:
  exe: interproscan.sh
  # Possible alternative:
  # exe <- /erdos/adf/sw/interproscan-5.3-46.0/interproscan.sh
  params: -appl TIGRFAM,SMART,SUPERFAMILY,Gene3D,PIRSF,Pfam,Coils

# HMMer
hmmer:
  exe: hmmscan
  db: /srv/shiny-server/legume.genefam.fam1.M65K.hmm
  # Unused:
  # params: [...]
  # target_families: [...]/07_family_fasta

############

